apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: devops-toolkit
  namespace: clusters
spec:
  repo: "https://github.com/donhighmsft/fleet-examples.git"
  branch: main
  targetNamespace: default
  paths:
  - single-cluster/manifests
  targets:
  - name: cust1
    clusterSelector:
      matchLabels:
        env: cust1
  - name: cust2
    clusterSelector:
      matchLabels:
        env: cust2
  - name: cust3
    clusterGroup: cust3
