apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: devops-toolkit
  # This namespace is special and auto-wired to deploy to the local cluster
  namespace: fleet-local
spec:
  # Everything from this repo will be ran in this cluster. You trust me right?
  repo: "https://github.com/donhighmsft/rancher-fleet-demo"
  paths:
    - manifests