helm:
  chart: "./"
targetCustomizations:
- name: cust1
  helm:
    values:
      image:
        tag: 2.7.0
  clusterSelector:
    matchLabels:
      env: cust1
- name: cust2
  helm:
    values:
      image:
        tag: 2.7.0
  clusterSelector:
    matchLabels:
      env: cust2
- name: cust3
  helm:
    values:
      image:
        tag: 2.7.0
  clusterSelector:
    matchLabels:
      env: cust3
